from __future__ import annotations

from .types import WorkerResponse
from ..llm import LLMClient
from ..models import AgentRole, TaskRecord, TaskType


def execute_specialist(task: TaskRecord, llm_client: LLMClient) -> WorkerResponse:
    if llm_client.enabled:
        llm_result = llm_client.generate_worker_output(task)
        return WorkerResponse(
            summary=llm_result["summary"],
            artifacts={
                **llm_result["artifacts"],
                "execution_mode": llm_result.get("mode", "llm"),
            },
        )

    if task.task_type == TaskType.PROMPT_ENHANCE:
        seed = str(task.payload.get("seed_prompt", "")).strip()
        title = str(task.payload.get("title", "agent")).strip()
        target_file = str(task.payload.get("target_file", "")).strip()
        enhanced = (
            "---\n"
            "mode: agent\n"
            f"description: Enhanced prompt generated by orchestrator for {title}.\n"
            "tools:\n"
            "  - changes\n"
            "  - codebase\n"
            "  - terminal\n"
            "---\n\n"
            "You are a high-agency specialist working under the orchestrator.\n"
            "Prioritize execution, explicit acceptance criteria, and verifiable outputs.\n\n"
            "Base Prompt Input:\n"
            f"{seed}\n"
        )
        return WorkerResponse(
            summary="Enhanced orchestrator-provided prompt and prepared it for storage.",
            artifacts={
                "enhanced_prompt": enhanced,
                "target_file": target_file,
                "title": title,
                "execution_mode": "deterministic",
            },
        )

    if task.role == AgentRole.ORCHESTRATOR:
        return WorkerResponse(
            summary="Created phased execution plan and delegated first specialist task.",
            artifacts={
                "phases": [
                    "context_index",
                    "product_framing",
                    "architecture",
                    "build",
                    "security_audit",
                    "qa",
                    "docs_update",
                    "memory_snapshot",
                ],
                "next_role": AgentRole.PRODUCT_MANAGER.value,
                "execution_mode": "deterministic",
            },
        )

    if task.role == AgentRole.PRODUCT_MANAGER:
        return WorkerResponse(
            summary="Mapped objective to MVP scope and acceptance criteria.",
            artifacts={
                "mvp_scope": ["core user journey", "admin panel", "basic analytics"],
                "acceptance_criteria": [
                    "User can complete primary workflow",
                    "Admin can view core metrics",
                    "System records auditable events",
                ],
                "next_role": AgentRole.SYSTEM_ARCHITECT.value,
                "execution_mode": "deterministic",
            },
        )

    if task.role == AgentRole.SYSTEM_ARCHITECT:
        return WorkerResponse(
            summary="Produced architecture defaults, contracts, and reliability controls.",
            artifacts={
                "stack": "FastAPI + PostgreSQL + React",
                "contracts": ["REST API v1", "event log schema"],
                "next_role": AgentRole.WEBAPP_BUILDER.value,
                "execution_mode": "deterministic",
            },
        )

    if task.role == AgentRole.WEBAPP_BUILDER:
        return WorkerResponse(
            summary="Implemented first vertical slice aligned to acceptance criteria.",
            artifacts={
                "slice": "auth + project setup + first endpoint",
                "tests_added": ["api smoke test", "auth guard test"],
                "next_role": AgentRole.SECURITY_AUDITOR.value,
                "execution_mode": "deterministic",
            },
        )

    if task.role == AgentRole.SECURITY_AUDITOR:
        return WorkerResponse(
            summary="Completed security audit and produced risk-ranked remediation guidance.",
            artifacts={
                "security_recommendation": "pass",
                "findings": [
                    {"severity": "low", "item": "Add stricter CSP defaults in production."},
                    {"severity": "low", "item": "Rotate non-production test secrets monthly."},
                ],
                "next_role": AgentRole.QA_RELIABILITY.value,
                "execution_mode": "deterministic",
            },
        )

    if task.role == AgentRole.QA_RELIABILITY:
        return WorkerResponse(
            summary="Validated build slice and generated release recommendation.",
            artifacts={
                "release_recommendation": "ship",
                "critical_findings": [],
                "next_role": AgentRole.DOCUMENTATION_AGENT.value,
                "execution_mode": "deterministic",
            },
        )

    if task.role == AgentRole.DOCUMENTATION_AGENT:
        return WorkerResponse(
            summary="Updated architecture and change documentation for current run.",
            artifacts={
                "architecture_notes": "Architecture remains service-oriented with orchestrator-led delegation and tenant-isolated runtime API.",
                "change_notes": "Run completed through orchestrator, PM, architect, builder, QA, and memory stages with dependency graph and retries.",
                "next_role": AgentRole.MEMORY_STEWARD.value,
                "execution_mode": "deterministic",
            },
        )

    return WorkerResponse(
        summary="Persisted run context and decisions for future retrieval.",
        artifacts={
            "snapshot": "run summary captured",
            "next_role": None,
            "execution_mode": "deterministic",
        },
    )
