from __future__ import annotations

from typing import Dict

from datetime import datetime
from pathlib import Path


class DocsStore:
    def __init__(self, repo_root: Path) -> None:
        self.docs_dir = repo_root / "docs" / "autogenerated"
        self.docs_dir.mkdir(parents=True, exist_ok=True)

    def update(self, *, run_id: str, objective: str, architecture_notes: str, change_notes: str) -> Dict[str, str]:
        stamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        architecture_path = self.docs_dir / "ARCHITECTURE.md"
        changes_path = self.docs_dir / "CHANGES.md"

        self._append_section(
            architecture_path,
            f"## {stamp} | Run {run_id}\n\n"
            f"Objective: {objective}\n\n"
            f"Architecture Notes:\n{architecture_notes}\n",
        )

        self._append_section(
            changes_path,
            f"## {stamp} | Run {run_id}\n\n"
            f"Objective: {objective}\n\n"
            f"Changes:\n{change_notes}\n",
        )

        return {
            "architecture_doc": str(architecture_path),
            "changes_doc": str(changes_path),
        }

    def _append_section(self, path: Path, section: str) -> None:
        if not path.exists():
            path.write_text("# Auto Generated Project Documentation\n\n", encoding="utf-8")
        existing = path.read_text(encoding="utf-8")
        path.write_text(existing + "\n" + section + "\n", encoding="utf-8")
